# Generated by Django 5.0.7 on 2024-08-06 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mensaje', models.TextField()),
                ('pregunta1', models.CharField(max_length=200)),
                ('pregunta2', models.CharField(max_length=200)),
                ('pregunta3', models.CharField(max_length=200)),
                ('pregunta4', models.CharField(max_length=200)),
                ('pregunta5', models.CharField(max_length=200)),
            ],
        ),
    ]
